# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        export SECRET_KEY = '539c578978c2fed91113d896f1d6b09c17b8e473d4bc2254c9ba6c16a9568e3a'
        export DEBUG = True
        export JWT_SECRET_KEY = 'c457690c111152b57157e0fb'
        export DATABASE_URL = 'postgres://ehxlysmxwjwuau:92a571a764b03a940c0946b3e958b214d63844444b5202e33d2ce579701e72e6@ec2-54-147-33-38.compute-1.amazonaws.com:5432/deshnrtleg1kc3'
        pytest
